[package]
name = "magpie"
version = "0.3.2"
description = "A smart clipboard manager for macOS"
authors = ["Kirk Lin"]
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
# The `_lib` suffix may seem redundant but it is necessary
# to make the lib name unique and wouldn't conflict with the bin name.
# This seems to be only an issue on Windows, see https://github.com/rust-lang/cargo/issues/8519
name = "magpie_lib"
crate-type = [
  "staticlib",
  "cdylib",
  "rlib"
]

[build-dependencies]
tauri-build = { version = "2.6.0", features = [] }

[dependencies]
tauri = { version = "2.11.0", features = [
  "macos-private-api",
  "tray-icon",
  "protocol-asset",
  "image-png"
] }
tauri-plugin-opener = "2.5.4"
serde = { version = "1", features = [ "derive" ] }
serde_json = "1"
tauri-plugin-clipboard-manager = "2.3.2"
tauri-plugin-global-shortcut = "2.3.1"
tauri-plugin-autostart = "2.5.1"
tauri-plugin-sql = { version = "2.4.0", features = [ "sqlite" ] }
tauri-plugin-store = "2.4.3"
tauri-plugin-fs = "2.5.1"
tauri-plugin-notification = "2.3.3"
tauri-plugin-positioner = "2.3.1"
tauri-plugin-single-instance = "2.4.2"
tokio = { version = "1.52.1", features = [ "full" ] }
chrono = { version = "0.4.44", features = [ "serde" ] }
regex = "1.12.3"
sha2 = "0.11.0"
hex = "0.4.3"
png = "0.17"
log = "0.4.29"
objc2 = "0.6.4"
objc2-app-kit = { version = "0.3.2", features = ["NSPasteboard", "NSPasteboardItem", "NSWorkspace", "NSRunningApplication", "NSImage", "NSBitmapImageRep", "NSImageRep", "NSGraphicsContext", "NSSavePanel", "NSOpenPanel", "NSPanel", "NSApplication"] }
objc2-foundation = { version = "0.3.2", features = [
  "NSString",
  "NSArray",
  "NSData",
  "NSURL",
  "NSPathUtilities",
  "NSObject",
  "NSDictionary"
] }
sqlx = { version = "0.8.6", features = [
  "runtime-tokio",
  "sqlite"
] }
env_logger = "0.11.10"
core-graphics = "0.25.0"
dirs = "6.0.0"
core-foundation = "0.10.1"

[profile.release]
codegen-units = 1
lto = true
opt-level = "s"
strip = true
