//! macOS platform adapters.
//!
//! All the NSPasteboard / AppKit / CoreGraphics FFI and the main-thread
//! dispatch it requires — previously scattered across
//! `clipboard/{monitor,native,paste}.rs` — lives here, behind the
//! [`Clipboard`] and [`Paster`] ports.

use std::sync::mpsc;
use std::time::Duration;

use tauri::AppHandle;
use tauri_plugin_clipboard_manager::ClipboardExt;

use super::{AppInfo, Captured, Clipboard, Paster, PasterCapabilities, WritePayload};

// ---------------------------------------------------------------------------
// Clipboard
// ---------------------------------------------------------------------------

pub struct MacClipboard {
    app: AppHandle,
}

impl MacClipboard {
    pub fn new(app: AppHandle) -> Self {
        Self { app }
    }
}

impl Clipboard for MacClipboard {
    fn change_token(&self) -> Option<i64> {
        current_change_count(&self.app)
    }

    fn read(&self) -> Option<Captured> {
        let app = &self.app;

        // Respect the de-facto-standard "concealed/transient" pasteboard markers
        // that password managers set, so we never persist passwords or other
        // sensitive, short-lived content.
        if pasteboard_is_concealed(app) {
            log::debug!("Skipping concealed/transient pasteboard content");
            return None;
        }

        // File URLs take priority (a file copy also exposes a text flavor).
        let file_paths = read_file_urls_from_pasteboard(app);
        if !file_paths.is_empty() {
            return Some(Captured::Files { paths: file_paths });
        }

        // Plain text.
        if let Ok(text) = app.clipboard().read_text() {
            if !text.is_empty() {
                return Some(Captured::Text { text, html: None });
            }
        }

        // Rich content that exposes only an HTML flavor with no plain-text
        // representation (some editors / web apps): capture the HTML and keep a
        // stripped plain-text version for display/search.
        if let Some(html) = read_html_from_pasteboard(app) {
            let plain = html_to_plain_text(&html);
            if !plain.is_empty() {
                return Some(Captured::Text { text: plain, html: Some(html) });
            }
        }

        // Image.
        if let Ok(image) = app.clipboard().read_image() {
            let rgba = image.rgba().to_vec();
            if !rgba.is_empty() {
                return Some(Captured::Image {
                    rgba,
                    width: image.width(),
                    height: image.height(),
                });
            }
        }

        log::debug!("Pasteboard changed but no recognizable content found");
        None
    }

    fn write(&self, payload: &WritePayload) -> Result<(), String> {
        match payload {
            WritePayload::Text(text) => self
                .app
                .clipboard()
                .write_text(text.as_str())
                .map_err(|e| format!("Failed to write to clipboard: {e}")),
            WritePayload::ImageFile(path) => write_png_to_pasteboard(&self.app, path),
            WritePayload::Files(paths) => write_files_to_pasteboard(paths),
        }
    }
}

/// Read the current pasteboard change count on the main thread. `None` if the
/// dispatch or read fails/times out — treated as "no reliable reading this
/// tick", NOT as "no change".
fn current_change_count(app_handle: &AppHandle) -> Option<i64> {
    let (tx, rx) = mpsc::channel();
    let dispatched = app_handle.run_on_main_thread(move || {
        use objc2::rc::autoreleasepool;
        use objc2_app_kit::NSPasteboard;

        let count = autoreleasepool(|_| {
            let pasteboard = NSPasteboard::generalPasteboard();
            pasteboard.changeCount() as i64
        });
        let _ = tx.send(count);
    });

    if dispatched.is_err() {
        return None;
    }

    rx.recv_timeout(Duration::from_millis(100)).ok()
}

/// True if the general pasteboard carries one of the standard markers used to
/// indicate sensitive/transient content that should not be recorded.
fn pasteboard_is_concealed(app_handle: &AppHandle) -> bool {
    let (tx, rx) = mpsc::channel();
    let dispatched = app_handle.run_on_main_thread(move || {
        use objc2::rc::autoreleasepool;
        use objc2_app_kit::NSPasteboard;

        let concealed = autoreleasepool(|_| {
            let pasteboard = NSPasteboard::generalPasteboard();
            NSPasteboard::types(&pasteboard).is_some_and(|types| {
                types.iter().any(|t| {
                    matches!(
                        t.to_string().as_str(),
                        "org.nspasteboard.ConcealedType"
                            | "org.nspasteboard.TransientType"
                            | "org.nspasteboard.AutoGeneratedType"
                    )
                })
            })
        });
        let _ = tx.send(concealed);
    });

    if dispatched.is_err() {
        return false;
    }

    rx.recv_timeout(Duration::from_millis(100)).unwrap_or(false)
}

/// Read file URLs from NSPasteboard. Must dispatch to the main thread since
/// NSPasteboard is not thread-safe.
fn read_file_urls_from_pasteboard(app_handle: &AppHandle) -> Vec<String> {
    let (tx, rx) = mpsc::channel();
    let dispatched = app_handle.run_on_main_thread(move || {
        use objc2::rc::autoreleasepool;
        use objc2_app_kit::NSPasteboard;
        use objc2_foundation::{NSArray, NSString, NSURL};

        let result = autoreleasepool(|_| {
            let pasteboard = NSPasteboard::generalPasteboard();

            // Check if the pasteboard contains file URLs.
            let types = NSPasteboard::types(&pasteboard);
            let has_file_url = types.map_or(false, |ts| {
                ts.iter().any(|t| {
                    let s = t.to_string();
                    s == "public.file-url" || s == "NSFilenamesPboardType"
                })
            });

            if !has_file_url {
                return vec![];
            }

            // Method 1: NSFilenamesPboardType returns actual file paths.
            // propertyListForType returns an untyped object; downcast it (a
            // runtime class check) instead of transmuting, so a malformed
            // pasteboard falls through to Method 2 rather than risking UB.
            let filenames_type = NSString::from_str("NSFilenamesPboardType");
            if let Some(array) = pasteboard
                .propertyListForType(&filenames_type)
                .and_then(|obj| obj.downcast::<NSArray>().ok())
            {
                let mut paths: Vec<String> = Vec::new();
                for item in array.iter() {
                    if let Some(path) = item.downcast_ref::<NSString>() {
                        let p = path.to_string();
                        if !p.is_empty() {
                            paths.push(p);
                        }
                    }
                }

                if !paths.is_empty() {
                    return paths;
                }
            }

            // Method 2: read NSURL from pasteboard items and resolve via NSURL.
            let file_url_type = NSString::from_str("public.file-url");
            if let Some(items) = pasteboard.pasteboardItems() {
                let mut paths: Vec<String> = Vec::new();
                for item in items.iter() {
                    if let Some(url_string) = item.stringForType(&file_url_type) {
                        let ns_url_str = url_string.to_string();
                        let ns_str = NSString::from_str(&ns_url_str);
                        if let Some(url) = NSURL::URLWithString(&ns_str) {
                            if let Some(file_path_url) = url.filePathURL() {
                                if let Some(path) = file_path_url.path() {
                                    let p = path.to_string();
                                    if !p.is_empty() {
                                        paths.push(p);
                                        continue;
                                    }
                                }
                            }
                            if let Some(path) = url.path() {
                                let p = path.to_string();
                                if !p.is_empty() {
                                    paths.push(p);
                                }
                            }
                        }
                    }
                }
                if !paths.is_empty() {
                    return paths;
                }
            }

            vec![]
        });
        let _ = tx.send(result);
    });

    if dispatched.is_err() {
        return vec![];
    }

    rx.recv_timeout(Duration::from_millis(200)).unwrap_or_default()
}

/// Read an HTML representation from the pasteboard, if present.
fn read_html_from_pasteboard(app_handle: &AppHandle) -> Option<String> {
    let (tx, rx) = mpsc::channel();
    let dispatched = app_handle.run_on_main_thread(move || {
        use objc2::rc::autoreleasepool;
        use objc2_app_kit::NSPasteboard;
        use objc2_foundation::NSString;

        let html = autoreleasepool(|_| {
            let pasteboard = NSPasteboard::generalPasteboard();
            let html_type = NSString::from_str("public.html");
            pasteboard
                .stringForType(&html_type)
                .map(|s| s.to_string())
                .filter(|s| !s.is_empty())
        });
        let _ = tx.send(html);
    });

    if dispatched.is_err() {
        return None;
    }

    rx.recv_timeout(Duration::from_millis(150)).ok().flatten()
}

/// Strip HTML markup down to a readable plain-text approximation.
fn html_to_plain_text(html: &str) -> String {
    use regex::Regex;

    // Drop <script>/<style> blocks entirely, then all remaining tags.
    let re = Regex::new(r"(?is)<(script|style)\b[^>]*>.*?</(script|style)>|<[^>]+>").unwrap();
    let stripped = re.replace_all(html, " ");
    let decoded = stripped
        .replace("&nbsp;", " ")
        .replace("&amp;", "&")
        .replace("&lt;", "<")
        .replace("&gt;", ">")
        .replace("&quot;", "\"")
        .replace("&#39;", "'");
    decoded.split_whitespace().collect::<Vec<_>>().join(" ")
}

/// Read a PNG file and write it to the general pasteboard, dispatched to the
/// main thread (NSPasteboard is not thread-safe).
fn write_png_to_pasteboard(app_handle: &AppHandle, image_path: &str) -> Result<(), String> {
    let png_data =
        std::fs::read(image_path).map_err(|e| format!("Failed to read image file: {}", e))?;

    let (tx, rx) = mpsc::channel();
    let _ = app_handle.run_on_main_thread(move || {
        use objc2::rc::autoreleasepool;
        use objc2_app_kit::NSPasteboard;
        use objc2_foundation::{NSData, NSString};

        let result = autoreleasepool(|_| {
            let pasteboard = NSPasteboard::generalPasteboard();
            pasteboard.clearContents();
            let png_type = NSString::from_str("public.png");
            let ns_data = NSData::with_bytes(&png_data);
            pasteboard.setData_forType(Some(&ns_data), &png_type)
        });
        let _ = tx.send(result);
    });

    let success = rx.recv().map_err(|e| e.to_string())?;
    if success {
        Ok(())
    } else {
        Err("Failed to write image to pasteboard".to_string())
    }
}

/// Write file paths to NSPasteboard as file URLs.
fn write_files_to_pasteboard(file_paths: &[String]) -> Result<(), String> {
    use objc2::rc::autoreleasepool;
    use objc2_app_kit::NSPasteboard;
    use objc2_foundation::{NSArray, NSString};

    autoreleasepool(|_| {
        let pasteboard = NSPasteboard::generalPasteboard();
        pasteboard.clearContents();

        let filenames_type = NSString::from_str("NSFilenamesPboardType");
        let file_url_type = NSString::from_str("public.file-url");
        let types = NSArray::from_retained_slice(&[
            NSString::from_str("NSFilenamesPboardType"),
            NSString::from_str("public.file-url"),
        ]);
        // SAFETY: declaring pasteboard types with no owner is safe.
        unsafe { pasteboard.declareTypes_owner(&types, None) };

        let ns_paths: Vec<_> = file_paths.iter().map(|p| NSString::from_str(p)).collect();
        let ns_array = NSArray::from_retained_slice(&ns_paths);

        // SAFETY: a valid NSArray<NSString> matches NSFilenamesPboardType.
        let success = unsafe { pasteboard.setPropertyList_forType(&ns_array, &filenames_type) };

        // Also set the first file as a file URL for apps that prefer
        // public.file-url.
        if let Some(first_path) = file_paths.first() {
            let encoded = format!("file://{}", first_path.replace(' ', "%20"));
            let url_str = NSString::from_str(&encoded);
            pasteboard.setString_forType(&url_str, &file_url_type);
        }

        if success {
            Ok(())
        } else {
            Err("Failed to write file paths to pasteboard".to_string())
        }
    })
}

// ---------------------------------------------------------------------------
// Paster
// ---------------------------------------------------------------------------

pub struct MacPaster {
    app: AppHandle,
}

impl MacPaster {
    pub fn new(app: AppHandle) -> Self {
        Self { app }
    }
}

impl Paster for MacPaster {
    fn frontmost_app(&self) -> AppInfo {
        let (tx, rx) = mpsc::channel();

        let dispatched = self.app.run_on_main_thread(move || {
            use objc2::rc::autoreleasepool;
            use objc2_app_kit::NSWorkspace;

            let result = autoreleasepool(|_| {
                let workspace = NSWorkspace::sharedWorkspace();
                if let Some(app) = workspace.frontmostApplication() {
                    let bundle_id = app.bundleIdentifier().map(|s| s.to_string());
                    let name = app.localizedName().map(|s| s.to_string());
                    (bundle_id, name)
                } else {
                    (None, None)
                }
            });
            let _ = tx.send(result);
        });

        if dispatched.is_err() {
            return AppInfo::default();
        }

        // Bounded wait: never hang the caller if the main thread is busy.
        let (bundle_id, name) = rx
            .recv_timeout(Duration::from_millis(200))
            .unwrap_or((None, None));
        AppInfo { bundle_id, name }
    }

    fn activate_app(&self, app_id: &str) -> bool {
        use objc2_app_kit::NSRunningApplication;
        use objc2_foundation::NSString;

        let bid = app_id.to_string();
        let (tx, rx) = mpsc::channel();
        let dispatched = self.app.run_on_main_thread(move || {
            let ns_bid = NSString::from_str(&bid);
            let apps =
                unsafe { NSRunningApplication::runningApplicationsWithBundleIdentifier(&ns_bid) };
            let activated = if apps.count() > 0 {
                let app = unsafe { apps.objectAtIndex(0) };
                #[allow(deprecated)]
                let _ = unsafe {
                    app.activateWithOptions(
                        objc2_app_kit::NSApplicationActivationOptions::ActivateIgnoringOtherApps,
                    )
                };
                true
            } else {
                false
            };
            let _ = tx.send(activated);
        });

        if dispatched.is_err() {
            return false;
        }
        rx.recv_timeout(Duration::from_millis(300)).unwrap_or(false)
    }

    fn paste(&self) -> Result<(), String> {
        // CGEvent key synthesis is silently discarded by macOS unless the app
        // has Accessibility access. Detect that up front so the paste fails
        // loudly (with a notification) instead of pretending to succeed — the
        // content is already on the clipboard, so the user can paste manually.
        if !crate::check_accessibility_permission() {
            use tauri_plugin_notification::NotificationExt;
            let _ = self
                .app
                .notification()
                .builder()
                .title("Magpie 无法自动粘贴")
                .body("内容已复制到剪贴板。请在「系统设置 → 隐私与安全性 → 辅助功能」中开启 Magpie 以启用自动粘贴。")
                .show();
            return Err("缺少辅助功能权限，无法模拟粘贴".to_string());
        }

        simulate_paste_keystroke();
        Ok(())
    }

    fn capabilities(&self) -> PasterCapabilities {
        PasterCapabilities {
            can_paste: true,
            can_activate_app: true,
        }
    }
}

/// Simulate Cmd+V using CGEvent. More reliable than osascript and needs only
/// Accessibility access (not separate System Events permission).
fn simulate_paste_keystroke() {
    use core_graphics::event::{CGEvent, CGEventFlags, CGKeyCode};
    use core_graphics::event_source::{CGEventSource, CGEventSourceStateID};

    // Key code 9 = 'V' on macOS.
    const V_KEY: CGKeyCode = 9;

    let source = match CGEventSource::new(CGEventSourceStateID::HIDSystemState) {
        Ok(s) => s,
        Err(_) => {
            log::error!("[Paste] Failed to create CGEventSource");
            return;
        }
    };

    let key_down = match CGEvent::new_keyboard_event(source.clone(), V_KEY, true) {
        Ok(e) => e,
        Err(_) => {
            log::error!("[Paste] Failed to create key down event");
            return;
        }
    };
    key_down.set_flags(CGEventFlags::CGEventFlagCommand);
    key_down.post(core_graphics::event::CGEventTapLocation::HID);

    let key_up = match CGEvent::new_keyboard_event(source, V_KEY, false) {
        Ok(e) => e,
        Err(_) => {
            log::error!("[Paste] Failed to create key up event");
            return;
        }
    };
    key_up.set_flags(CGEventFlags::CGEventFlagCommand);
    key_up.post(core_graphics::event::CGEventTapLocation::HID);

    log::debug!("[Paste] Simulated Cmd+V via CGEvent");
}
