//! macOS platform adapters.
//!
//! All the NSPasteboard / AppKit / CoreGraphics FFI and the main-thread
//! dispatch it requires lives here, behind the [`Clipboard`], [`Paster`] and
//! [`Icons`] ports.

use std::sync::mpsc;
use std::time::Duration;

use tauri::AppHandle;
use tauri_plugin_clipboard_manager::ClipboardExt;

use super::{
    AppInfo, Captured, Clipboard, FocusedWindow, Icons, Paster, PasterCapabilities, WritePayload,
};

// ---------------------------------------------------------------------------
// Clipboard
// ---------------------------------------------------------------------------

pub struct MacClipboard {
    app: AppHandle,
}

impl MacClipboard {
    pub fn new(app: AppHandle) -> Self {
        Self { app }
    }
}

impl Clipboard for MacClipboard {
    fn change_token(&self) -> Option<i64> {
        current_change_count(&self.app)
    }

    fn read(&self) -> Result<Option<Captured>, String> {
        let app = &self.app;

        // Respect the de-facto-standard "concealed/transient" pasteboard markers
        // that password managers set, so we never persist passwords or other
        // sensitive, short-lived content.
        if pasteboard_is_concealed(app) {
            log::debug!("Skipping concealed/transient pasteboard content");
            return Ok(None);
        }

        // File URLs take priority (a file copy also exposes a text flavor).
        let file_paths = read_file_urls_from_pasteboard(app);
        if !file_paths.is_empty() {
            return Ok(Some(Captured::Files { paths: file_paths }));
        }

        // Plain text.
        if let Ok(text) = app.clipboard().read_text() {
            if !text.is_empty() {
                return Ok(Some(Captured::Text { text, html: None }));
            }
        }

        // Rich content that exposes only an HTML flavor with no plain-text
        // representation (some editors / web apps): capture the HTML and keep a
        // stripped plain-text version for display/search.
        if let Some(html) = read_html_from_pasteboard(app) {
            let plain = super::html_to_plain_text(&html);
            if !plain.is_empty() {
                return Ok(Some(Captured::Text { text: plain, html: Some(html) }));
            }
        }

        // Image.
        if let Ok(image) = app.clipboard().read_image() {
            let rgba = image.rgba().to_vec();
            if !rgba.is_empty() {
                return Ok(Some(Captured::Image {
                    rgba,
                    width: image.width(),
                    height: image.height(),
                }));
            }
        }

        log::debug!("Pasteboard changed but no recognizable content found");
        Ok(None)
    }

    fn write(&self, payload: &WritePayload) -> Result<(), String> {
        match payload {
            WritePayload::Text(text) => self
                .app
                .clipboard()
                .write_text(text.as_str())
                .map_err(|e| format!("Failed to write to clipboard: {e}")),
            WritePayload::ImageFile(path) => write_png_to_pasteboard(&self.app, path),
            WritePayload::Files(paths) => write_files_to_pasteboard(paths),
        }
    }
}

/// Read the current pasteboard change count on the main thread. `None` if the
/// dispatch or read fails/times out — treated as "no reliable reading this
/// tick", NOT as "no change".
fn current_change_count(app_handle: &AppHandle) -> Option<i64> {
    let (tx, rx) = mpsc::channel();
    let dispatched = app_handle.run_on_main_thread(move || {
        use objc2::rc::autoreleasepool;
        use objc2_app_kit::NSPasteboard;

        let count = autoreleasepool(|_| {
            let pasteboard = NSPasteboard::generalPasteboard();
            pasteboard.changeCount() as i64
        });
        let _ = tx.send(count);
    });

    if dispatched.is_err() {
        return None;
    }

    rx.recv_timeout(Duration::from_millis(100)).ok()
}

/// True if the general pasteboard carries one of the standard markers used to
/// indicate sensitive/transient content that should not be recorded.
fn pasteboard_is_concealed(app_handle: &AppHandle) -> bool {
    let (tx, rx) = mpsc::channel();
    let dispatched = app_handle.run_on_main_thread(move || {
        use objc2::rc::autoreleasepool;
        use objc2_app_kit::NSPasteboard;

        let concealed = autoreleasepool(|_| {
            let pasteboard = NSPasteboard::generalPasteboard();
            NSPasteboard::types(&pasteboard).is_some_and(|types| {
                types.iter().any(|t| {
                    matches!(
                        t.to_string().as_str(),
                        "org.nspasteboard.ConcealedType"
                            | "org.nspasteboard.TransientType"
                            | "org.nspasteboard.AutoGeneratedType"
                    )
                })
            })
        });
        let _ = tx.send(concealed);
    });

    if dispatched.is_err() {
        return false;
    }

    rx.recv_timeout(Duration::from_millis(100)).unwrap_or(false)
}

/// Read file URLs from NSPasteboard. Must dispatch to the main thread since
/// NSPasteboard is not thread-safe.
fn read_file_urls_from_pasteboard(app_handle: &AppHandle) -> Vec<String> {
    let (tx, rx) = mpsc::channel();
    let dispatched = app_handle.run_on_main_thread(move || {
        use objc2::rc::autoreleasepool;
        use objc2_app_kit::NSPasteboard;
        use objc2_foundation::{NSArray, NSString, NSURL};

        let result = autoreleasepool(|_| {
            let pasteboard = NSPasteboard::generalPasteboard();

            // Check if the pasteboard contains file URLs.
            let types = NSPasteboard::types(&pasteboard);
            let has_file_url = types.map_or(false, |ts| {
                ts.iter().any(|t| {
                    let s = t.to_string();
                    s == "public.file-url" || s == "NSFilenamesPboardType"
                })
            });

            if !has_file_url {
                return vec![];
            }

            // Method 1: NSFilenamesPboardType returns actual file paths.
            // propertyListForType returns an untyped object; downcast it (a
            // runtime class check) instead of transmuting, so a malformed
            // pasteboard falls through to Method 2 rather than risking UB.
            let filenames_type = NSString::from_str("NSFilenamesPboardType");
            if let Some(array) = pasteboard
                .propertyListForType(&filenames_type)
                .and_then(|obj| obj.downcast::<NSArray>().ok())
            {
                let mut paths: Vec<String> = Vec::new();
                for item in array.iter() {
                    if let Some(path) = item.downcast_ref::<NSString>() {
                        let p = path.to_string();
                        if !p.is_empty() {
                            paths.push(p);
                        }
                    }
                }

                if !paths.is_empty() {
                    return paths;
                }
            }

            // Method 2: read NSURL from pasteboard items and resolve via NSURL.
            let file_url_type = NSString::from_str("public.file-url");
            if let Some(items) = pasteboard.pasteboardItems() {
                let mut paths: Vec<String> = Vec::new();
                for item in items.iter() {
                    if let Some(url_string) = item.stringForType(&file_url_type) {
                        let ns_url_str = url_string.to_string();
                        let ns_str = NSString::from_str(&ns_url_str);
                        if let Some(url) = NSURL::URLWithString(&ns_str) {
                            if let Some(file_path_url) = url.filePathURL() {
                                if let Some(path) = file_path_url.path() {
                                    let p = path.to_string();
                                    if !p.is_empty() {
                                        paths.push(p);
                                        continue;
                                    }
                                }
                            }
                            if let Some(path) = url.path() {
                                let p = path.to_string();
                                if !p.is_empty() {
                                    paths.push(p);
                                }
                            }
                        }
                    }
                }
                if !paths.is_empty() {
                    return paths;
                }
            }

            vec![]
        });
        let _ = tx.send(result);
    });

    if dispatched.is_err() {
        return vec![];
    }

    rx.recv_timeout(Duration::from_millis(200)).unwrap_or_default()
}

/// Read an HTML representation from the pasteboard, if present.
fn read_html_from_pasteboard(app_handle: &AppHandle) -> Option<String> {
    let (tx, rx) = mpsc::channel();
    let dispatched = app_handle.run_on_main_thread(move || {
        use objc2::rc::autoreleasepool;
        use objc2_app_kit::NSPasteboard;
        use objc2_foundation::NSString;

        let html = autoreleasepool(|_| {
            let pasteboard = NSPasteboard::generalPasteboard();
            let html_type = NSString::from_str("public.html");
            pasteboard
                .stringForType(&html_type)
                .map(|s| s.to_string())
                .filter(|s| !s.is_empty())
        });
        let _ = tx.send(html);
    });

    if dispatched.is_err() {
        return None;
    }

    rx.recv_timeout(Duration::from_millis(150)).ok().flatten()
}

/// Read a PNG file and write it to the general pasteboard, dispatched to the
/// main thread (NSPasteboard is not thread-safe).
fn write_png_to_pasteboard(app_handle: &AppHandle, image_path: &str) -> Result<(), String> {
    let png_data =
        std::fs::read(image_path).map_err(|e| format!("Failed to read image file: {}", e))?;

    let (tx, rx) = mpsc::channel();
    let _ = app_handle.run_on_main_thread(move || {
        use objc2::rc::autoreleasepool;
        use objc2_app_kit::NSPasteboard;
        use objc2_foundation::{NSData, NSString};

        let result = autoreleasepool(|_| {
            let pasteboard = NSPasteboard::generalPasteboard();
            pasteboard.clearContents();
            let png_type = NSString::from_str("public.png");
            let ns_data = NSData::with_bytes(&png_data);
            pasteboard.setData_forType(Some(&ns_data), &png_type)
        });
        let _ = tx.send(result);
    });

    let success = rx.recv().map_err(|e| e.to_string())?;
    if success {
        Ok(())
    } else {
        Err("Failed to write image to pasteboard".to_string())
    }
}

/// Write file paths to NSPasteboard as file URLs.
fn write_files_to_pasteboard(file_paths: &[String]) -> Result<(), String> {
    use objc2::rc::autoreleasepool;
    use objc2_app_kit::NSPasteboard;
    use objc2_foundation::{NSArray, NSString};

    autoreleasepool(|_| {
        let pasteboard = NSPasteboard::generalPasteboard();
        pasteboard.clearContents();

        let filenames_type = NSString::from_str("NSFilenamesPboardType");
        let file_url_type = NSString::from_str("public.file-url");
        let types = NSArray::from_retained_slice(&[
            NSString::from_str("NSFilenamesPboardType"),
            NSString::from_str("public.file-url"),
        ]);
        // SAFETY: declaring pasteboard types with no owner is safe.
        unsafe { pasteboard.declareTypes_owner(&types, None) };

        let ns_paths: Vec<_> = file_paths.iter().map(|p| NSString::from_str(p)).collect();
        let ns_array = NSArray::from_retained_slice(&ns_paths);

        // SAFETY: a valid NSArray<NSString> matches NSFilenamesPboardType.
        let success = unsafe { pasteboard.setPropertyList_forType(&ns_array, &filenames_type) };

        // Also set the first file as a file URL for apps that prefer
        // public.file-url.
        if let Some(first_path) = file_paths.first() {
            let encoded = format!("file://{}", first_path.replace(' ', "%20"));
            let url_str = NSString::from_str(&encoded);
            pasteboard.setString_forType(&url_str, &file_url_type);
        }

        if success {
            Ok(())
        } else {
            Err("Failed to write file paths to pasteboard".to_string())
        }
    })
}

// ---------------------------------------------------------------------------
// Paster
// ---------------------------------------------------------------------------

pub struct MacPaster {
    app: AppHandle,
}

impl MacPaster {
    pub fn new(app: AppHandle) -> Self {
        Self { app }
    }
}

impl Paster for MacPaster {
    fn focused_window(&self) -> FocusedWindow {
        let (tx, rx) = mpsc::channel();
        let dispatched = self.app.run_on_main_thread(move || {
            use objc2::rc::autoreleasepool;
            use objc2_app_kit::NSWorkspace;

            let pid = autoreleasepool(|_| {
                NSWorkspace::sharedWorkspace()
                    .frontmostApplication()
                    .map(|app| app.processIdentifier())
                    .filter(|pid| *pid > 0)
                    .map(|pid| pid as u32)
            });
            let _ = tx.send(pid);
        });

        if dispatched.is_err() {
            return FocusedWindow::default();
        }
        // Bounded wait: never hang the caller if the main thread is busy.
        let pid = rx.recv_timeout(Duration::from_millis(200)).ok().flatten();
        FocusedWindow { pid, window: None }
    }

    fn frontmost_app(&self) -> AppInfo {
        let (tx, rx) = mpsc::channel();

        let dispatched = self.app.run_on_main_thread(move || {
            use objc2::rc::autoreleasepool;
            use objc2_app_kit::NSWorkspace;

            let result = autoreleasepool(|_| {
                let workspace = NSWorkspace::sharedWorkspace();
                if let Some(app) = workspace.frontmostApplication() {
                    AppInfo {
                        app_id: app.bundleIdentifier().map(|s| s.to_string()),
                        name: app.localizedName().map(|s| s.to_string()),
                        focus: FocusedWindow {
                            pid: Some(app.processIdentifier())
                                .filter(|pid| *pid > 0)
                                .map(|pid| pid as u32),
                            window: None,
                        },
                    }
                } else {
                    AppInfo::default()
                }
            });
            let _ = tx.send(result);
        });

        if dispatched.is_err() {
            return AppInfo::default();
        }

        // Bounded wait: never hang the caller if the main thread is busy.
        rx.recv_timeout(Duration::from_millis(200)).unwrap_or_default()
    }

    fn activate(&self, target: &AppInfo) -> bool {
        use objc2_app_kit::NSRunningApplication;
        use objc2_foundation::NSString;

        let bundle_id = target.app_id.clone();
        let pid = target.focus.pid;
        let (tx, rx) = mpsc::channel();
        let dispatched = self.app.run_on_main_thread(move || {
            // Prefer the exact process that was frontmost; the bundle id covers
            // an app that was relaunched in between.
            let app = pid
                .and_then(|pid| NSRunningApplication::runningApplicationWithProcessIdentifier(pid as i32))
                .or_else(|| {
                    let ns_bid = NSString::from_str(bundle_id.as_deref()?);
                    let apps = NSRunningApplication::runningApplicationsWithBundleIdentifier(&ns_bid);
                    (apps.count() > 0).then(|| apps.objectAtIndex(0))
                });
            #[allow(deprecated)]
            let activated = app.is_some_and(|app| {
                app.activateWithOptions(
                    objc2_app_kit::NSApplicationActivationOptions::ActivateIgnoringOtherApps,
                )
            });
            let _ = tx.send(activated);
        });

        if dispatched.is_err() {
            return false;
        }
        rx.recv_timeout(Duration::from_millis(300)).unwrap_or(false)
    }

    fn hide_and_restore_focus(&self, _previous: Option<&AppInfo>) -> Result<(), String> {
        // Hiding the whole application makes macOS re-activate whichever app
        // was active before it, which is exactly the one Magpie was summoned
        // from.
        self.app.hide().map_err(|e| e.to_string())
    }

    fn refocus_magpie(&self) {
        use tauri::Manager;
        if let Some(window) = self.app.get_webview_window("main") {
            let _ = window.set_focus();
        }
    }

    fn paste(&self) -> Result<(), String> {
        // CGEvent key synthesis is silently discarded by macOS unless the app
        // has Accessibility access. Detect that up front so the paste fails
        // loudly (with a notification) instead of pretending to succeed — the
        // content is already on the clipboard, so the user can paste manually.
        if !crate::check_accessibility_permission() {
            use tauri_plugin_notification::NotificationExt;
            let loc = crate::i18n::read_locale(&self.app);
            let _ = self
                .app
                .notification()
                .builder()
                .title(crate::i18n::tr(loc, "notify.paste_failed_title"))
                .body(crate::i18n::tr(loc, "notify.paste_failed_body"))
                .show();
            return Err(crate::i18n::tr(loc, "err.no_accessibility").to_string());
        }

        simulate_paste_keystroke();
        Ok(())
    }

    fn capabilities(&self) -> PasterCapabilities {
        PasterCapabilities {
            can_paste: true,
            can_activate_app: true,
            can_read_focus: true,
        }
    }
}

/// Simulate Cmd+V using CGEvent. More reliable than osascript and needs only
/// Accessibility access (not separate System Events permission).
fn simulate_paste_keystroke() {
    use core_graphics::event::{CGEvent, CGEventFlags, CGKeyCode};
    use core_graphics::event_source::{CGEventSource, CGEventSourceStateID};

    // Key code 9 = 'V' on macOS.
    const V_KEY: CGKeyCode = 9;

    let source = match CGEventSource::new(CGEventSourceStateID::HIDSystemState) {
        Ok(s) => s,
        Err(_) => {
            log::error!("[Paste] Failed to create CGEventSource");
            return;
        }
    };

    let key_down = match CGEvent::new_keyboard_event(source.clone(), V_KEY, true) {
        Ok(e) => e,
        Err(_) => {
            log::error!("[Paste] Failed to create key down event");
            return;
        }
    };
    key_down.set_flags(CGEventFlags::CGEventFlagCommand);
    key_down.post(core_graphics::event::CGEventTapLocation::HID);

    let key_up = match CGEvent::new_keyboard_event(source, V_KEY, false) {
        Ok(e) => e,
        Err(_) => {
            log::error!("[Paste] Failed to create key up event");
            return;
        }
    };
    key_up.set_flags(CGEventFlags::CGEventFlagCommand);
    key_up.post(core_graphics::event::CGEventTapLocation::HID);

    log::debug!("[Paste] Simulated Cmd+V via CGEvent");
}

// ---------------------------------------------------------------------------
// Icons
// ---------------------------------------------------------------------------

pub struct MacIcons;

impl Icons for MacIcons {
    fn app_icon(&self, app_id: &str) -> Result<String, String> {
        use objc2_app_kit::NSWorkspace;
        use objc2_foundation::NSString;

        let workspace = NSWorkspace::sharedWorkspace();
        let ns_bundle_id = NSString::from_str(app_id);
        let url = workspace
            .URLForApplicationWithBundleIdentifier(&ns_bundle_id)
            .ok_or_else(|| format!("App not found: {}", app_id))?;
        let path = url.path().ok_or("No path for app URL")?;
        fetch_icon_for_path(&path, 32.0)
    }

    fn file_icon(&self, path: &str) -> Result<String, String> {
        use objc2_foundation::NSString;
        // A larger size than app icons: file icons also fill the preview panel.
        fetch_icon_for_path(&NSString::from_str(path), 128.0)
    }
}

/// Render the icon for `path` as a base64 PNG data URL.
///
/// The whole body runs inside an `autoreleasepool`, and that is load-bearing
/// rather than tidiness. Every step here hands back an autoreleased object:
/// `iconForFile:` returns an NSImage carrying EVERY representation of the icon
/// (16pt through 1024pt), and `TIFFRepresentation` serializes all of them into
/// one UNCOMPRESSED NSData — megabytes per call. Tauri commands run on runtime
/// worker threads that have no pool of their own, so without this those objects
/// were never released: scrolling the history once leaked hundreds of MB into
/// the Foundation zone, and it never came back. `get_file_icon` deliberately
/// has no Rust-side cache, so it is called for every distinct file path, which
/// is what turned the leak into gigabytes.
fn fetch_icon_for_path(path: &objc2_foundation::NSString, size: f64) -> Result<String, String> {
    use objc2::rc::autoreleasepool;

    autoreleasepool(|_| {
        use objc2::rc::Retained;
        use objc2_app_kit::{NSBitmapImageFileType, NSBitmapImageRep, NSWorkspace};
        use objc2_foundation::NSData;

        let workspace = NSWorkspace::sharedWorkspace();
        let icon = workspace.iconForFile(path);

        // Set a reasonable size for the icon. This shrinks what gets drawn, but
        // NOT what TIFFRepresentation serializes below — hence the pool.
        icon.setSize(objc2_foundation::NSSize::new(size, size));

        let tiff_data: Retained<NSData> = icon
            .TIFFRepresentation()
            .ok_or("Failed to get TIFF representation")?;
        let bitmap_rep = NSBitmapImageRep::imageRepWithData(&tiff_data)
            .ok_or("Failed to create bitmap rep")?;
        let png_data = unsafe {
            bitmap_rep.representationUsingType_properties(
                NSBitmapImageFileType::PNG,
                &objc2_foundation::NSDictionary::new(),
            )
        }
        .ok_or("Failed to convert to PNG")?;

        // Copy the bytes out BEFORE the pool drains — png_data dies with it.
        Ok(super::png_data_url(&png_data.to_vec()))
    })
}

#[cfg(test)]
mod tests {
    use super::*;

    /// Resident set size of this process, in MB.
    fn rss_mb() -> u64 {
        let out = std::process::Command::new("ps")
            .args(["-o", "rss=", "-p", &std::process::id().to_string()])
            .output()
            .expect("ps");
        String::from_utf8_lossy(&out.stdout).trim().parse::<u64>().unwrap_or(0) / 1024
    }

    /// Byte-for-byte what `fetch_icon_for_path` does, minus the autoreleasepool.
    /// Exists purely so the test can A/B the pool against its absence in ONE
    /// process — comparing across runs is too noisy to prove anything.
    fn fetch_icon_unpooled(path: &objc2_foundation::NSString, size: f64) -> Result<String, String> {
        use objc2_app_kit::{NSBitmapImageFileType, NSBitmapImageRep, NSWorkspace};

        let workspace = NSWorkspace::sharedWorkspace();
        let icon = workspace.iconForFile(path);
        icon.setSize(objc2_foundation::NSSize::new(size, size));
        let tiff_data = icon.TIFFRepresentation().ok_or("no tiff")?;
        let bitmap_rep = NSBitmapImageRep::imageRepWithData(&tiff_data).ok_or("no rep")?;
        let png_data = unsafe {
            bitmap_rep.representationUsingType_properties(
                NSBitmapImageFileType::PNG,
                &objc2_foundation::NSDictionary::new(),
            )
        }
        .ok_or("no png")?;
        Ok(super::super::png_data_url(&png_data.to_vec()))
    }

    /// Icon fetching must not grow memory without bound.
    ///
    /// `fetch_icon_for_path` builds an NSImage holding every representation of
    /// the icon and serializes all of them into one uncompressed TIFF. Without
    /// an `autoreleasepool` around it those objects are never released on a
    /// Tauri worker thread, and repeated calls (one per distinct file path in
    /// the history list, uncached by design) grow the Foundation zone into the
    /// gigabytes. Ignored by default: it measures process RSS, so it is timing
    /// and machine dependent rather than a clean unit assertion.
    ///
    /// Run with: cargo test --lib icon_fetch_does_not_leak -- --ignored --nocapture
    #[test]
    #[ignore = "measures process RSS; run explicitly"]
    fn icon_fetch_does_not_leak() {
        const N: usize = 400;
        let path = objc2_foundation::NSString::from_str("/Applications");

        // Warm up so first-call initialization counts against neither variant.
        for _ in 0..50 {
            let _ = fetch_icon_for_path(&path, 128.0);
        }

        let base = rss_mb();
        for _ in 0..N {
            let _ = fetch_icon_unpooled(&path, 128.0);
        }
        let unpooled = rss_mb().saturating_sub(base);

        // Reclaim what the unpooled run stranded, so the pooled measurement
        // starts from a settled baseline rather than inheriting that growth.
        objc2::rc::autoreleasepool(|_| {});
        let base = rss_mb();
        for _ in 0..N {
            let _ = fetch_icon_for_path(&path, 128.0);
        }
        let pooled = rss_mb().saturating_sub(base);

        println!("over {N} icon fetches — without pool: +{unpooled} MB, with pool: +{pooled} MB");
        assert!(
            pooled < 50,
            "pooled icon fetching still grew {pooled} MB over {N} calls"
        );
    }
}
