// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
  getClipboardEntries: (query: ClipboardQuery) => typedError<ClipboardEntry[], AppError>(__TAURI_INVOKE("get_clipboard_entries", { query })),
  deleteClipboardEntry: (id: number) => typedError<null, AppError>(__TAURI_INVOKE("delete_clipboard_entry", { id })),
  clearClipboardHistory: () => typedError<null, AppError>(__TAURI_INVOKE("clear_clipboard_history")),
  togglePinEntry: (id: number) => typedError<boolean, AppError>(__TAURI_INVOKE("toggle_pin_entry", { id })),
  renameClipboardEntry: (id: number, name: string) => typedError<null, AppError>(__TAURI_INVOKE("rename_clipboard_entry", { id, name })),
  pasteClipboardEntry: (text: string) => typedError<null, AppError>(__TAURI_INVOKE("paste_clipboard_entry", { text })),
  /**  Paste an image entry by writing the saved PNG to the clipboard, then pasting. */
  pasteImageEntry: (imagePath: string) => typedError<null, AppError>(__TAURI_INVOKE("paste_image_entry", { imagePath })),
  /**  Copy an image entry to the clipboard without pasting */
  copyImageEntry: (imagePath: string) => typedError<null, AppError>(__TAURI_INVOKE("copy_image_entry", { imagePath })),
  /**
   *  Resolve the image the history list should actually load for `image_path`.
   *
   *  Returns a small pre-scaled thumbnail when one applies, else the original
   *  path. Rendering the original in a 24pt row forced the WebView to decode the
   *  full bitmap (tens of MB for a screenshot) purely to throw the pixels away;
   *  see `clipboard::thumbnail` for the full rationale.
   *
   *  Generation is lazy so the ~1000 images captured before thumbnails existed
   *  get one on first display, and it runs on the blocking pool because decoding
   *  and re-encoding a PNG is CPU-bound work that must not stall the async
   *  runtime that also drives clipboard capture.
   */
  getThumbnail: (imagePath: string) => typedError<string, AppError>(__TAURI_INVOKE("get_thumbnail", { imagePath })),
  copyClipboardEntry: (text: string) => typedError<null, AppError>(__TAURI_INVOKE("copy_clipboard_entry", { text })),
  pasteAsPlainText: (text: string) => typedError<null, AppError>(__TAURI_INVOKE("paste_as_plain_text", { text })),
  pasteFileEntry: (filePathsJson: string) => typedError<null, AppError>(__TAURI_INVOKE("paste_file_entry", { filePathsJson })),
  copyFileEntry: (filePathsJson: string) => typedError<null, AppError>(__TAURI_INVOKE("copy_file_entry", { filePathsJson })),
  /**  Update the text content of a clipboard entry (Edit Content action) */
  updateEntryContent: (id: number, content: string) => typedError<null, AppError>(__TAURI_INVOKE("update_entry_content", { id, content })),
  /**  Append text to the current clipboard content */
  appendToClipboard: (text: string) => typedError<null, AppError>(__TAURI_INVOKE("append_to_clipboard", { text })),
  /**
   *  Save clipboard entry content to a file using a native save dialog.
   *  Returns false when the user cancelled.
   */
  saveEntryAsFile: (content: string, defaultName: string) => typedError<boolean, AppError>(__TAURI_INVOKE("save_entry_as_file", { content, defaultName })),
  /**
   *  Paste content to the target app while keeping the Magpie window visible.
   *  Activates the target app (window stays on screen due to always_on_top),
   *  simulates ⌘/Ctrl+V, then re-focuses Magpie.
   */
  pasteAndKeepWindow: (text: string) => typedError<null, AppError>(__TAURI_INVOKE("paste_and_keep_window", { text })),
  /**  Paste an image entry while keeping the Magpie window visible. */
  pasteImageAndKeepWindow: (imagePath: string) => typedError<null, AppError>(__TAURI_INVOKE("paste_image_and_keep_window", { imagePath })),
  /**  Paste file entries while keeping the Magpie window visible. */
  pasteFileAndKeepWindow: (filePathsJson: string) => typedError<null, AppError>(__TAURI_INVOKE("paste_file_and_keep_window", { filePathsJson })),
  /**
   *  Export clipboard history to a JSON file via native save dialog.
   *  Returns the number of entries exported, or 0 if the user cancelled.
   */
  exportClipboardHistory: () => typedError<number, AppError>(__TAURI_INVOKE("export_clipboard_history")),
  /**
   *  Import clipboard history from a JSON file via native open dialog.
   *  Returns the number of entries imported (skipping duplicates).
   */
  importClipboardHistory: () => typedError<number, AppError>(__TAURI_INVOKE("import_clipboard_history")),
  getDefaultSettings: () => __TAURI_INVOKE<AppSettings>("get_default_settings"),
  /**
   *  Re-register the global shortcut at runtime. An invalid or unregisterable
   *  shortcut is rejected, and the app keeps a working one.
   */
  updateGlobalShortcut: (shortcut: string) => typedError<null, AppError>(__TAURI_INVOKE("update_global_shortcut", { shortcut })),
  /**
   *  How the global shortcut is bound on this desktop: recorded in Magpie, owned
   *  by the desktop, or to be set up by the user in the desktop's settings.
   */
  getShortcutBinding: () => __TAURI_INVOKE<ShortcutBinding>("get_shortcut_binding"),
  /**  Open the desktop's own dialog for changing the global shortcut. */
  configureSystemShortcut: () => typedError<null, AppError>(__TAURI_INVOKE("configure_system_shortcut")),
  /**  Show or hide the menu bar tray icon at runtime. */
  setTrayVisible: (visible: boolean) => typedError<null, AppError>(__TAURI_INVOKE("set_tray_visible", { visible })),
  /**
   *  Rebuild the native tray + app menu in the currently-persisted locale.
   *  Called by the frontend right after the language setting changes, so the OS
   *  menus switch language without requiring a restart.
   */
  relocalizeMenus: () => __TAURI_INVOKE<void>("relocalize_menus"),
  /**
   *  Get the icon of an application as a PNG data URL. `app_id` is the
   *  entry's `source_app`: a bundle id (macOS), an executable path (Windows) or a
   *  desktop entry id (Linux).
   */
  getAppIcon: (appId: string) => typedError<string, AppError>(__TAURI_INVOKE("get_app_icon", { appId })),
  /**
   *  Get the icon the system file browser shows for `file_path`, as a PNG data
   *  URL. Not cached here: the frontend keeps its own per-path cache.
   */
  getFileIcon: (filePath: string) => typedError<string, AppError>(__TAURI_INVOKE("get_file_icon", { filePath })),
  /**
   *  What paste-back can do on this OS and desktop, so the UI only offers
   *  actions that work.
   */
  getPasterCapabilities: () => __TAURI_INVOKE<PasterCapabilities>("get_paster_capabilities"),
  /**  Hide the main window */
  hideWindow: () => __TAURI_INVOKE<void>("hide_window"),
};

/* Types */
/**
 *  Application-level error for the Rust side, surfaced to the frontend.
 *
 *  Serializable + `specta::Type` and internally tagged on `kind`, so commands
 *  can return `Result<T, AppError>` and the generated TypeScript bindings get a
 *  typed discriminated union:
 *  `{ kind: "DbUnavailable" } | { kind: "Sql"; message: string } | …`.
 *
 *  `Sql`/`Io` carry a `message: String` rather than the underlying
 *  `sqlx::Error` / `std::io::Error` (which are not serializable); the manual
 *  `From` impls below stringify them. `Display` still emits the same stable
 *  prefixes (`db_unavailable:` / `sql:` / …), so any remaining
 *  `Result<T, String>` command keeps its old wire string.
 */
export type AppError = { kind: "DbUnavailable" } | { kind: "Sql"; message: string } | { kind: "Io"; message: string } | { kind: "Validation"; message: string } | { kind: "Other"; message: string };

/**  Settings */
export interface AppSettings {
  history_retention_days: number;
  max_history_count: number;
  default_action: string;
  global_shortcut: string;
  excluded_apps: string[];
  theme: string;
  launch_at_login: boolean;
  move_to_top_on_use: boolean;
  show_menu_bar_icon: boolean;
}

/**  A clipboard history entry */
export interface ClipboardEntry {
  id: number;
  content_type: string;
  text_content: string | null;
  html_content: string | null;
  image_path: string | null;
  file_paths: string | null;
  source_app: string | null;
  source_app_name: string | null;
  custom_name: string | null;
  is_pinned: boolean;
  is_favorite: boolean;
  content_hash: string;
  content_preview: string | null;
  byte_size: number;
  created_at: string;
  accessed_at: string;
  access_count: number;
}

/**  Query parameters for fetching clipboard entries */
export interface ClipboardQuery {
  search: string | null;
  content_type: string | null;
  pinned_only: boolean;
  limit: number;
  offset: number;
}

/**  What a platform's paster can actually do, so the UI can degrade honestly. */
export interface PasterCapabilities {
  /**  A paste keystroke can be synthesized into the focused app. */
  can_paste: boolean;
  /**
   *  Another application can be brought to the foreground, which "paste and
   *  keep window open" needs.
   */
  can_activate_app: boolean;
  /**  The focused window can be read, so the UI can name the paste target. */
  can_read_focus: boolean;
}

/**
 *  How the toggle shortcut is bound on this desktop, for the settings screen.
 *  The desktop-owned variants only occur on Linux but belong to the shared
 *  IPC type.
 */
export type ShortcutBinding
/**  Magpie registers the shortcut itself; the user records it in Settings. */
  = { kind: "native" }
/**  The desktop owns the shortcut (Wayland GlobalShortcuts portal). */
    | { kind: "portal";
      /**  The trigger as the desktop words it, once assigned. */
      trigger: string | null;
      /**  Whether the desktop can open its own dialog to change it. */
      can_configure: boolean;
      /**
       *  What a shortcut bound in the desktop's keyboard settings runs, for
       *  desktops whose portal leaves the key unassigned (Hyprland, niri) or
       *  when the user declined the desktop's prompt.
       */
      command: string; }
/**
 *  Nothing can register a shortcut for Magpie: bind one to `command` in
 *  the desktop's keyboard settings.
 */
      | { kind: "manual"; command: string };

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
  try {
    return { status: "ok", data: await result };
  } catch (e) {
    if (e instanceof Error) {
      throw e;
    }
    return { status: "error", error: e as any };
  }
}
